{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.bigqueryServiceAccount }}
{{- $sa := $svc.bigqueryServiceAccount }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-backend.serviceFullname" (dict "root" $root "serviceName" $name) }}-bigquery-sa
  labels:
    {{- include "platform-backend.labels" (dict "root" $root "serviceName" $name) | nindent 4 }}
type: Opaque
stringData:
  service-account.json: {{ dict "type" $sa.type "project_id" $sa.projectId "private_key_id" $sa.privateKeyId "private_key" $sa.privateKey "client_email" $sa.clientEmail "client_id" $sa.clientId "auth_uri" $sa.authUri "token_uri" $sa.tokenUri "auth_provider_x509_cert_url" $sa.authProviderX509CertUrl "client_x509_cert_url" $sa.clientX509CertUrl "universe_domain" $sa.universeDomain | toJson | quote }}
---
{{- end }}
{{- end }}
